=== limit-case/glassbench/data/schema/sample-meta.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/limit-case/glassbench/data/schema/sample-meta.schema.json",
  "title": "GlassBench sample scene meta.json",
  "type": "object",
  "required": [
    "seed",
    "variant",
    "intrinsics",
    "baseline",
    "cam_matrix_world",
    "objects",
    "n_opaque"
  ],
  "properties": {
    "seed": {
      "type": "integer"
    },
    "variant": {
      "enum": [
        "d415",
        "d435",
        "l515"
      ]
    },
    "intrinsics": {
      "type": "object",
      "required": [
        "fx",
        "fy",
        "cx",
        "cy",
        "width",
        "height"
      ],
      "properties": {
        "fx": {
          "type": "number"
        },
        "fy": {
          "type": "number"
        },
        "cx": {
          "type": "number"
        },
        "cy": {
          "type": "number"
        },
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        }
      }
    },
    "baseline": {
      "type": [
        "number",
        "null"
      ]
    },
    "cam_matrix_world": {
      "type": "array",
      "minItems": 4,
      "maxItems": 4,
      "items": {
        "type": "array",
        "minItems": 4,
        "maxItems": 4,
        "items": {
          "type": "number"
        }
      }
    },
    "camera_dist": {
      "type": "number"
    },
    "camera_elev_deg": {
      "type": "number"
    },
    "exposure": {
      "type": "number"
    },
    "texture": {
      "type": "string"
    },
    "wall": {
      "type": "boolean"
    },
    "world": {
      "type": "string"
    },
    "n_lights": {
      "type": "integer"
    },
    "objects": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "model",
          "plastic"
        ],
        "properties": {
          "model": {
            "type": "string"
          },
          "plastic": {
            "type": "boolean"
          }
        }
      }
    },
    "n_opaque": {
      "type": "integer"
    },
    "total": {
      "type": "number"
    }
  }
}

=== limit-case/glassbench/examples/sample/l515/00000/meta.json
{
 "cam_matrix_world": [
  [
   0.67000812292099,
   -0.6734346151351929,
   0.3123699128627777,
   0.36003756523132324
  ],
  [
   0.7421011328697205,
   0.5966219305992126,
   -0.3054966330528259,
   -0.21803751587867737
  ],
  [
   0.01936527155339718,
   0.436495304107666,
   0.8994981050491333,
   0.4321179687976837
  ],
  [
   0.0,
   0.0,
   0.0,
   1.0
  ]
 ],
 "exposure": -7.891939836930252,
 "seed": 0,
 "variant": "l515",
 "intrinsics": {
  "fx": 451.2015,
  "fy": 451.40150000000006,
  "cx": 325.4805,
  "cy": 182.7205,
  "width": 640,
  "height": 360
 },
 "baseline": null,
 "texture": "checker",
 "wall": false,
 "world": "sky",
 "n_lights": 3,
 "objects": [
  {
   "model": "tree-bath-bomb.obj",
   "plastic": true
  }
 ],
 "n_opaque": 1,
 "camera_dist": 0.4359297444782375,
 "camera_elev_deg": 64.09217648848966,
 "total": 2.593330144882202
}

=== limit-case/glassbench/examples/sample/d435/00002/meta.json
{
 "cam_matrix_world": [
  [
   -0.981644332408905,
   -0.15669609606266022,
   0.10872317850589752,
   0.39065319299697876
  ],
  [
   0.1903839260339737,
   -0.7712308764457703,
   0.6074182391166687,
   0.5557911992073059
  ],
  [
   -0.011329401284456253,
   0.6169677972793579,
   0.7869068384170532,
   0.5825795531272888
  ],
  [
   0.0,
   0.0,
   0.0,
   1.0
  ]
 ],
 "exposure": -3.8610742185385525,
 "seed": 2,
 "variant": "d435",
 "intrinsics": {
  "fx": 347.9973856787208,
  "fy": 347.9973856787208,
  "cx": 320.0,
  "cy": 180.0,
  "width": 640,
  "height": 360
 },
 "baseline": 0.05,
 "texture": "noise",
 "wall": true,
 "world": "sky",
 "n_lights": 2,
 "objects": [
  {
   "model": "glass-round-potion.obj",
   "plastic": false
  }
 ],
 "n_opaque": 0,
 "camera_dist": 0.6895091815488074,
 "camera_elev_deg": 51.89738496877133,
 "total": 9.204110145568848
}

=== limit-case/glassbench/examples/sample/d435/00001/meta.json
{
 "cam_matrix_world": [
  [
   -0.37358558177948,
   0.6770250201225281,
   -0.6340906023979187,
   -0.4256436824798584
  ],
  [
   -0.9275954961776733,
   -0.2722245156764984,
   0.25585222244262695,
   0.2191397249698639
  ],
  [
   0.0006033268291503191,
   0.6837623119354248,
   0.7297045588493347,
   0.5287520289421082
  ],
  [
   0.0,
   0.0,
   0.0,
   1.0
  ]
 ],
 "exposure": -7.180615795215405,
 "seed": 1,
 "variant": "d435",
 "intrinsics": {
  "fx": 347.9973856787208,
  "fy": 347.9973856787208,
  "cx": 320.0,
  "cy": 180.0,
  "width": 640,
  "height": 360
 },
 "baseline": 0.05,
 "texture": "checker",
 "wall": false,
 "world": "uniform",
 "n_lights": 3,
 "objects": [
  {
   "model": "star-bath-bomb.obj",
   "plastic": false
  },
  {
   "model": "flower-bath-bomb.obj",
   "plastic": false
  },
  {
   "model": "glass-square-potion.obj",
   "plastic": false
  },
  {
   "model": "square-plastic-bottle.obj",
   "plastic": true
  }
 ],
 "n_opaque": 0,
 "camera_dist": 0.669794332200931,
 "camera_elev_deg": 46.86163592257381,
 "total": 8.22157621383667
}

=== limit-case/glassbench/examples/sample/d435/00000/meta.json
{
 "cam_matrix_world": [
  [
   0.67000812292099,
   -0.6734346151351929,
   0.3123699128627777,
   0.36003756523132324
  ],
  [
   0.7421011328697205,
   0.5966219305992126,
   -0.3054966330528259,
   -0.21803751587867737
  ],
  [
   0.01936527155339718,
   0.436495304107666,
   0.8994981050491333,
   0.4321179687976837
  ],
  [
   0.0,
   0.0,
   0.0,
   1.0
  ]
 ],
 "exposure": -7.839426851345385,
 "seed": 0,
 "variant": "d435",
 "intrinsics": {
  "fx": 347.9973856787208,
  "fy": 347.9973856787208,
  "cx": 320.0,
  "cy": 180.0,
  "width": 640,
  "height": 360
 },
 "baseline": 0.05,
 "texture": "checker",
 "wall": false,
 "world": "sky",
 "n_lights": 3,
 "objects": [
  {
   "model": "tree-bath-bomb.obj",
   "plastic": true
  }
 ],
 "n_opaque": 1,
 "camera_dist": 0.4359297444782375,
 "camera_elev_deg": 64.09217648848966,
 "total": 7.09581995010376
}

=== limit-case/glassbench/examples/sample/l515/00002/meta.json
{
 "cam_matrix_world": [
  [
   -0.981644332408905,
   -0.15669609606266022,
   0.10872317850589752,
   0.39065319299697876
  ],
  [
   0.1903839260339737,
   -0.7712308764457703,
   0.6074182391166687,
   0.5557911992073059
  ],
  [
   -0.011329401284456253,
   0.6169677972793579,
   0.7869068384170532,
   0.5825795531272888
  ],
  [
   0.0,
   0.0,
   0.0,
   1.0
  ]
 ],
 "exposure": -3.8893839683852374,
 "seed": 2,
 "variant": "l515",
 "intrinsics": {
  "fx": 451.2015,
  "fy": 451.40150000000006,
  "cx": 325.4805,
  "cy": 182.7205,
  "width": 640,
  "height": 360
 },
 "baseline": null,
 "texture": "noise",
 "wall": true,
 "world": "sky",
 "n_lights": 2,
 "objects": [
  {
   "model": "glass-round-potion.obj",
   "plastic": false
  }
 ],
 "n_opaque": 0,
 "camera_dist": 0.6895091815488074,
 "camera_elev_deg": 51.89738496877133,
 "total": 3.1859290599823
}
